// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package sseries

import (
	"fmt"

	"github.com/tobgu/go-qcache/dataframe/filter"
	"github.com/tobgu/go-qcache/dataframe/internal/index"
	"github.com/tobgu/go-qcache/dataframe/internal/series"
)

// Code generated from template/series.go DO NOT EDIT

type Series struct {
	data []string
}

func New(d []string) Series {
	return Series{data: d}
}

func (s Series) Filter(index index.Int, c filter.Comparator, comparatee interface{}, bIndex index.Bool) error {
	// TODO: Also make it possible to compare to values in other column
	compFunc, ok := filterFuncs[c]
	if !ok {
		return fmt.Errorf("invalid comparison operator for string, %v", c)
	}

	return compFunc(index, s.data, comparatee, bIndex)
}

func (s Series) Equals(index index.Int, other series.Series, otherIndex index.Int) bool {
	otherI, ok := other.(Series)
	if !ok {
		return false
	}

	for ix, x := range index {
		if s.data[x] != otherI.data[otherIndex[ix]] {
			return false
		}
	}

	return true
}

func (s Series) subset(index index.Int) Series {
	data := make([]string, 0, len(index))
	for _, ix := range index {
		data = append(data, s.data[ix])
	}

	return Series{data: data}
}

func (s Series) Subset(index index.Int) series.Series {
	return s.subset(index)
}

func (s Series) Comparable(reverse bool) series.Comparable {
	if reverse {
		return Comparable{data: s.data, ltValue: series.GreaterThan, gtValue: series.LessThan}
	}

	return Comparable{data: s.data, ltValue: series.LessThan, gtValue: series.GreaterThan}
}

func (s Series) String() string {
	return fmt.Sprintf("%v", s.data)
}

func (s Series) Aggregate(indices []index.Int, fnName string) (series.Series, error) {
	fn, ok := aggregations[fnName]
	if !ok {
		return nil, fmt.Errorf("aggregation function %s is not defined for in series", fnName)
	}

	data := make([]string, 0, len(indices))
	for _, ix := range indices {
		subS := s.subset(ix)
		data = append(data, fn(subS.data))
	}

	return Series{data: data}, nil
}

type Comparable struct {
	data    []string
	ltValue series.CompareResult
	gtValue series.CompareResult
}
