// Code generated by "stringer -type=argCount"; DO NOT EDIT

package qframe

import "fmt"

const _argCount_name = "argCountOneargCountTwo"

var _argCount_index = [...]uint8{0, 11, 22}

func (i argCount) String() string {
	if i >= argCount(len(_argCount_index)-1) {
		return fmt.Sprintf("argCount(%d)", i)
	}
	return _argCount_name[_argCount_index[i]:_argCount_index[i+1]]
}
