// Code generated by "stringer -type=FunctionType"; DO NOT EDIT

package types

import "fmt"

const _FunctionType_name = "FunctionTypeUndefinedFunctionTypeIntFunctionTypeFloatFunctionTypeBoolFunctionTypeString"

var _FunctionType_index = [...]uint8{0, 21, 36, 53, 69, 87}

func (i FunctionType) String() string {
	if i >= FunctionType(len(_FunctionType_index)-1) {
		return fmt.Sprintf("FunctionType(%d)", i)
	}
	return _FunctionType_name[_FunctionType_index[i]:_FunctionType_index[i+1]]
}
