// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package iseries

import (
	"fmt"

	"github.com/tobgu/qframe/internal/index"
	"github.com/tobgu/qframe/internal/series"
)

// Code generated from template/series.go DO NOT EDIT

type Series struct {
	data []int
}

func New(d []int) Series {
	return Series{data: d}
}

func Apply1(fn func(int) int, s series.Series, ix index.Int) (Series, error) {
	sI, ok := s.(Series)
	if !ok {
		return Series{}, fmt.Errorf("Apply2: invalid column type: %#v", s)
	}

	result := make([]int, len(sI.data))
	for _, i := range ix {
		result[i] = fn(sI.data[i])
	}

	return New(result), nil
}

func Apply2(fn func(int, int) int, s1, s2 series.Series, ix index.Int) (Series, error) {
	sI1, ok1 := s1.(Series)
	sI2, ok2 := s2.(Series)
	if !ok1 || !ok2 {
		return Series{}, fmt.Errorf("Apply2: invalid column type: %#v, %#v", s1, s2)
	}

	result := make([]int, len(sI1.data))
	for _, i := range ix {
		result[i] = fn(sI1.data[i], sI2.data[i])
	}

	return New(result), nil
}

func (s Series) subset(index index.Int) Series {
	data := make([]int, len(index))
	for i, ix := range index {
		data[i] = s.data[ix]
	}

	return Series{data: data}
}

func (s Series) Subset(index index.Int) series.Series {
	return s.subset(index)
}

func (s Series) Comparable(reverse bool) series.Comparable {
	if reverse {
		return Comparable{data: s.data, ltValue: series.GreaterThan, gtValue: series.LessThan}
	}

	return Comparable{data: s.data, ltValue: series.LessThan, gtValue: series.GreaterThan}
}

func (s Series) String() string {
	return fmt.Sprintf("%v", s.data)
}

func (s Series) Aggregate(indices []index.Int, fn interface{}) (series.Series, error) {
	var actualFn func([]int) int
	var ok bool

	switch t := fn.(type) {
	case string:
		actualFn, ok = aggregations[t]
		if !ok {
			return nil, fmt.Errorf("aggregation function %s is not defined for series", fn)
		}
	case func([]int) int:
		actualFn = t
	default:
		// TODO: Genny is buggy and won't let you use your own errors package.
		//       We use a standard error here for now.
		return nil, fmt.Errorf("invalid aggregation function type: %v", t)
	}

	data := make([]int, 0, len(indices))
	for _, ix := range indices {
		subS := s.subset(ix)
		data = append(data, actualFn(subS.data))
	}

	return Series{data: data}, nil
}

type Comparable struct {
	data    []int
	ltValue series.CompareResult
	gtValue series.CompareResult
}
