// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package scolumn

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE1a760eeDecodeGithubComTobguQframeInternalScolumn(in *jlexer.Lexer, out *JsonString) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(JsonString, 0, 8)
			} else {
				*out = JsonString{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *string
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(string)
				}
				*v1 = string(in.String())
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1a760eeEncodeGithubComTobguQframeInternalScolumn(out *jwriter.Writer, in JsonString) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				out.String(string(*v3))
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v JsonString) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1a760eeEncodeGithubComTobguQframeInternalScolumn(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JsonString) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1a760eeEncodeGithubComTobguQframeInternalScolumn(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JsonString) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1a760eeDecodeGithubComTobguQframeInternalScolumn(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JsonString) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1a760eeDecodeGithubComTobguQframeInternalScolumn(l, v)
}
